// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountChangeBox: typeof import('./../components/UserCenter/components/AccountChangeBox.vue')['default']
    BaseInfoBox: typeof import('./../components/HotBoxItem/components/BaseInfoBox.vue')['default']
    BetHistoryBox: typeof import('./../components/UserCenter/components/BetHistoryBox.vue')['default']
    Bracket: typeof import('./../components/Bracket/index.vue')['default']
    BracketNode: typeof import('./../components/Bracket/components/BracketNode.vue')['default']
    BulletinItem: typeof import('./../components/UserCenter/components/BulletinItem.vue')['default']
    BulletinListBox: typeof import('./../components/UserCenter/components/BulletinListBox.vue')['default']
    CenterHeader: typeof import('./../components/UserCenter/components/CenterHeader.vue')['default']
    ChampionBetItem: typeof import('./../components/ChampionBetItem/index.vue')['default']
    Clipboard: typeof import('./../components/Clipboard/index.vue')['default']
    Empty: typeof import('./../components/Empty/index.vue')['default']
    EndBetItem: typeof import('./../components/EndBetItem/index.vue')['default']
    FavoriteAndPointBox: typeof import('./../components/HotBoxItem/components/FavoriteAndPointBox.vue')['default']
    FilterCriteriaBox: typeof import('./../components/FilterCriteriaBox/index.vue')['default']
    GamePlayers: typeof import('./../components/Bracket/components/GamePlayers.vue')['default']
    HasLiveIcon: typeof import('./../components/HasLiveIcon/index.vue')['default']
    HistoryParlayItem: typeof import('./../components/UserCenter/components/HistoryParlayItem.vue')['default']
    HistorySingleItem: typeof import('./../components/UserCenter/components/HistorySingleItem.vue')['default']
    HotBoxItem: typeof import('./../components/HotBoxItem/index.vue')['default']
    IndexTemp: typeof import('./../components/LodingPage/index-temp.vue')['default']
    LangSelectBox: typeof import('./../components/LangSelectBox/index.vue')['default']
    LazyImage: typeof import('./../components/lazyImage/index.vue')['default']
    LiveIcon: typeof import('./../components/LiveIcon/index.vue')['default']
    LodingPage: typeof import('./../components/LodingPage/index.vue')['default']
    LogoDateBox: typeof import('./../components/UniversalBetItem/components/LogoDateBox.vue')['default']
    NearData: typeof import('./../components/UniversalBetItem/components/NearData.vue')['default']
    NoMore: typeof import('./../components/NoMore/index.vue')['default']
    PlacardAlert: typeof import('./../components/PlacardAlert/index.vue')['default']
    PlayNameBox: typeof import('./../components/HotBoxItem/components/PlayNameBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule0: typeof import('./../components/UserCenter/components/game-rule/en-us/rule0.vue')['default']
    Rule1: typeof import('./../components/UserCenter/components/game-rule/en-us/rule1.vue')['default']
    Rule2: typeof import('./../components/UserCenter/components/game-rule/en-us/rule2.vue')['default']
    Rule3: typeof import('./../components/UserCenter/components/game-rule/en-us/rule3.vue')['default']
    Rule4: typeof import('./../components/UserCenter/components/game-rule/en-us/rule4.vue')['default']
    RulesBox: typeof import('./../components/UserCenter/components/RulesBox.vue')['default']
    TeamBox: typeof import('./../components/ChampionBetItem/components/TeamBox.vue')['default']
    ThirdTeamBox: typeof import('./../components/HotBoxItem/components/ThirdTeamBox.vue')['default']
    TimePickerBox: typeof import('./../components/TimePickerBox/index.vue')['default']
    ToTopBox: typeof import('./../components/ToTopBox/index.vue')['default']
    UniversalBetItem: typeof import('./../components/UniversalBetItem/index.vue')['default']
    UserCenter: typeof import('./../components/UserCenter/index.vue')['default']
    VueCountTo: typeof import('./../components/VueCountTo/index.vue')['default']
  }
}
