/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Iconify: typeof import('./../components/Iconify/index.vue')['default']
    LiveBox: typeof import('./../components/LiveBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    VueCountTo: typeof import('./../components/VueCountTo/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Iconify: typeof import('./../components/Iconify/index.vue')['default']
  const LiveBox: typeof import('./../components/LiveBox/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  const VueCountTo: typeof import('./../components/VueCountTo/index.vue')['default']
}